# Generated by Django 5.2.4 on 2025-07-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0002_surveyins_surveyinitems_surveyphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontainerTerdeteksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kontainer', models.CharField(max_length=15, unique=True)),
                ('cont_size', models.CharField(blank=True, null=True)),
                ('cont_type', models.CharField(blank=True, null=True)),
                ('waktu_deteksi', models.DateTimeField(auto_now_add=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gambar_kontainer/')),
                ('probabilitas', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kontainer_terdeteksi',
            },
        ),
    ]
