# Generated by Django 5.2.4 on 2025-07-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0003_kontainerterdeteksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontainerterdeteksi',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('digunakan', 'Digunakan')], default='baru', max_length=20),
        ),
    ]
