# Generated by Django 5.2.4 on 2025-07-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0005_surveyinsnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinsnew',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
