# Generated by Django 5.2.4 on 2025-07-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0006_alter_surveyinsnew_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyinsnew',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='surveyinsnew',
            name='updated_by',
        ),
    ]
