# Generated by Django 5.2.4 on 2025-07-18 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0007_remove_surveyinsnew_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyinsnew',
            old_name='photo',
            new_name='foto',
        ),
    ]
