# Generated by Django 5.2.4 on 2025-07-21 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0008_rename_photo_surveyinsnew_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='surveyin_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='surveyor.surveyinsnew')),
            ],
            options={
                'db_table': 'surveyinsphoto',
            },
        ),
        migrations.DeleteModel(
            name='SurveyPhoto',
        ),
    ]
