# Generated by Django 5.2.4 on 2025-07-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaluser',
            name='token',
        ),
    ]
