# Generated by Django 5.2.4 on 2025-07-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_externaluser_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbalance',
            options={},
        ),
    ]
