# Generated by Django 5.2.4 on 2025-07-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_bbalance_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbalance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='id',
        ),
        migrations.AlterField(
            model_name='bbalance',
            name='bbalance_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
