# Generated by Django 5.1.4 on 2025-06-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='App ID'),
        ),
    ]
