# Generated by Django 5.2.4 on 2025-07-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('menu_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'superadmin_accessmenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=100)),
                ('icon_menu', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.IntegerField()),
                ('app_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'superadmin_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_submenu', models.CharField(max_length=100)),
                ('icon_submenu', models.CharField(max_length=100)),
                ('sort', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('menu_id', models.IntegerField()),
                ('urls', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'superadmin_submenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=150)),
                ('last_name', models.CharField(db_column='last_name', max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role_id', models.IntegerField()),
                ('app_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'login_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PresenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='absen_photos/')),
                ('type', models.CharField(choices=[('in', 'Masuk'), ('out', 'Pulang')], default='in', max_length=5)),
            ],
            options={
                'db_table': 'presence_log',
            },
        ),
        migrations.CreateModel(
            name='TrainingFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('encoding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_face',
            },
        ),
    ]
