# Generated by Django 5.1.4 on 2025-04-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservasi_id', models.CharField(max_length=50, unique=True)),
                ('data_container', models.TextField(help_text='Gabungan no container, dipisahkan koma')),
                ('data_truck', models.TextField(help_text='Gabungan no truck, dipisahkan koma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
