# Generated by Django 5.1.4 on 2025-04-29 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignee', '0002_alter_reservasi_reservasi_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservasi',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reservasi',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='data_container',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='data_truck',
            field=models.CharField(max_length=100),
        ),
    ]
