# Generated by Django 5.1.4 on 2025-04-30 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignee', '0003_remove_reservasi_created_at_reservasi_consignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Menunggu Konfirmasi'), (2, 'Dikonfirmasi'), (3, 'Ditolak'), (4, 'Selesai')], default=0),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
