# Generated by Django 5.1.4 on 2025-04-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignee', '0004_reservasi_created_at_reservasi_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='track_in',
            field=models.IntegerField(choices=[(0, 'Awaiting Approval'), (1, 'In Progress'), (2, 'Cancelled by Consignee'), (3, 'Cancelled by Admin')], default=0),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='track_out',
            field=models.IntegerField(choices=[(0, 'Awaiting Approval'), (1, 'In Progress'), (2, 'Cancelled by Consignee'), (3, 'Cancelled by Admin')], default=0),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='status',
            field=models.IntegerField(choices=[(0, 'Awaiting Approval'), (1, 'In Progress'), (2, 'Cancelled by Consignee'), (3, 'Cancelled by Admin')], default=0),
        ),
    ]
