# Generated by Django 5.1.4 on 2025-04-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignee', '0005_reservasi_track_in_reservasi_track_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasi',
            name='track_in',
            field=models.IntegerField(choices=[(0, 'Awaiting Schedule'), (1, 'Scheduled'), (2, 'Gate In'), (3, 'Inspection'), (4, 'Washing / Cleaning'), (5, 'EOR Check'), (6, 'Repair'), (7, 'Stacking')], null=True),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='track_out',
            field=models.IntegerField(choices=[(0, 'Awaiting Confirmation'), (1, 'Scheduled'), (2, 'Gate In'), (3, 'Inspection'), (4, 'Delivery Order Processing'), (5, 'Gate Out')], null=True),
        ),
    ]
