# Generated by Django 5.1.4 on 2025-04-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GateIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eir_in', models.DateField()),
                ('truck_no', models.CharField(max_length=15)),
                ('trucking_name', models.CharField(max_length=100)),
                ('path_foto', models.TextField()),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gate In',
                'verbose_name_plural': 'Gate Ins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GateOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eir_out', models.DateField()),
                ('foto_container', models.TextField()),
                ('no_container', models.CharField(max_length=20)),
                ('truck_no', models.CharField(max_length=15)),
                ('trucking_name', models.CharField(max_length=100)),
                ('path_foto', models.TextField()),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gate Out',
                'verbose_name_plural': 'Gate Outs',
                'ordering': ['-created_at'],
            },
        ),
    ]
