# Generated by Django 5.1.4 on 2025-06-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='app_id',
            field=models.CharField(default='intercon_enterprise_system', max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon_menu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sort',
            field=models.IntegerField(),
        ),
    ]
