# Generated by Django 5.1.4 on 2025-06-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_menu_app_id_alter_menu_icon_menu_alter_menu_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='nama_submenu',
            field=models.CharField(default='Submenu', max_length=100),
        ),
    ]
