# Generated by Django 5.1.4 on 2025-04-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_no', models.CharField(max_length=11, unique=True)),
                ('referal', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('customer_code', models.CharField(max_length=10)),
                ('container_type', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=5)),
                ('condition', models.CharField(max_length=5)),
                ('washing', models.CharField(max_length=5)),
                ('grade', models.CharField(max_length=2)),
                ('act_in', models.CharField(max_length=5)),
                ('manufacture', models.CharField(blank=True, max_length=7, null=True)),
                ('tare', models.CharField(blank=True, max_length=20, null=True)),
                ('payload', models.CharField(blank=True, max_length=20, null=True)),
                ('haulier', models.CharField(blank=True, max_length=20, null=True)),
                ('truck', models.CharField(blank=True, max_length=20, null=True)),
                ('washing_by', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
