# Generated by Django 5.1.4 on 2025-04-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_no', models.CharField(blank=True, max_length=20, null=True)),
                ('block', models.CharField(max_length=5)),
                ('spec', models.CharField(max_length=5)),
                ('row', models.CharField(max_length=5)),
                ('tier', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('block', 'spec', 'row', 'tier')},
            },
        ),
    ]
